[features]
seeds = false
skip-lint = false
[programs.localnet]
auto = "8i26WfxnU6aY12m9YPzzUtj11UrXXPJXT2YrDgzxFoV8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ademola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/auto.ts"
